In [3]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

- epochs : 470p 책 한권을 다 읽어서 학습하는것 
- batch : 한번 학습할때 마다 10p씩 끊어서 학습하라고 할 때 그것의 횟수 > 47일 소요

In [4]:
import numpy as np
import pandas as pd
np.random.seed(3)
tf.random.set_seed(3)

In [17]:
Data_set = np.loadtxt('dataset/ThoraricSurgery.csv',delimiter=',')

In [18]:
Data_set

0   1     2     3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0    293   1  3.80  2.80   0   0   0   0   0   0  12   0   0   0   1   0  62   
1      1   2  2.88  2.16   1   0   0   0   1   1  14   0   0   0   1   0  60   
2      8   2  3.19  2.50   1   0   0   0   1   0  11   0   0   1   1   0  66   
3     14   2  3.98  3.06   2   0   0   0   1   1  14   0   0   0   1   0  80   
4     17   2  2.21  1.88   0   0   1   0   0   0  12   0   0   0   1   0  56   
..   ...  ..   ...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   
465   98   6  3.04  2.40   2   0   0   0   1   0  11   0   0   0   1   0  76   
466  369   6  3.88  2.72   1   0   0   0   1   0  12   0   0   0   1   0  77   
467  406   6  5.36  3.96   1   0   0   0   1   0  12   0   0   0   0   0  62   
468   25   8  4.32  3.20   0   0   0   0   0   0  11   0   0   0   0   0  58   
469  447   8  5.20  4.10   0   0   0   0   0   0  12   0   0   0   0   0  49   

     17  
0     0  
1     0  
2     1  
3     1  
4     0  
..   ..  
465   0  
466   0  
467   0  
468   1  
469   0  

[470 rows x 18 columns]

In [20]:
x = Data_set[:,0:18]
y = Data_set[:,17]

TypeError: '(slice(None, None, None), slice(0, 18, None))' is an invalid key

In [14]:
x

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [13]:
y

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [9]:
x

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [11]:
# 딥러닝 구조를 결정 
model = Sequential()
# 모델을 설정하고 실행하는 부분 
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [12]:
# 모델 실행 
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=100,batch_size=10)

Epoch 1/100
47/47 [==============================] - 0s 894us/step - loss: 0.1485 - accuracy: 0.8426
Epoch 2/100
47/47 [==============================] - 0s 787us/step - loss: 0.1402 - accuracy: 0.8511
Epoch 3/100
47/47 [==============================] - 0s 851us/step - loss: 0.1433 - accuracy: 0.8489
Epoch 4/100
47/47 [==============================] - 0s 830us/step - loss: 0.1395 - accuracy: 0.8511
Epoch 5/100
47/47 [==============================] - 0s 830us/step - loss: 0.1386 - accuracy: 0.8468
Epoch 6/100
47/47 [==============================] - 0s 745us/step - loss: 0.1408 - accuracy: 0.8511
Epoch 7/100
47/47 [==============================] - 0s 788us/step - loss: 0.1335 - accuracy: 0.8489
Epoch 8/100
47/47 [==============================] - 0s 830us/step - loss: 0.1385 - accuracy: 0.8511
Epoch 9/100
47/47 [==============================] - 0s 809us/step - loss: 0.1379 - accuracy: 0.8383
Epoch 10/100
47/47 [==============================] - 0s 830us/step - loss: 0.1437 - accura